# Generated by Django 3.2.5 on 2022-06-11 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_auto_20220610_0202'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=1000)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='message',
            name='date',
            field=models.TextField(default='June 12, 2022'),
        ),
        migrations.AlterField(
            model_name='message',
            name='time',
            field=models.TextField(default='01:24AM'),
        ),
    ]
