# Generated by Django 3.2.5 on 2022-06-11 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_auto_20220612_0124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='time',
            field=models.TextField(default='01:36AM'),
        ),
    ]
